-- MODO BRÍGIDO — esquema inicial para Supabase
-- Ejecutar completo en Supabase > SQL Editor > New query > Run

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  timezone text not null default 'America/Santiago',
  calories_target integer not null default 2200 check (calories_target between 800 and 8000),
  protein_target integer not null default 160 check (protein_target between 20 and 500),
  steps_target integer not null default 7000 check (steps_target between 0 and 100000),
  weight_target numeric(6,2),
  waist_target numeric(6,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  log_date date not null,
  weight_kg numeric(6,2),
  waist_cm numeric(6,2),
  sleep_score smallint check (sleep_score between 1 and 5),
  energy_score smallint check (energy_score between 1 and 5),
  hunger_score smallint check (hunger_score between 1 and 5),
  cannabis boolean,
  calories integer check (calories >= 0),
  protein_g integer check (protein_g >= 0),
  steps integer check (steps >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, log_date)
);

create table if not exists public.exercise_library (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null check (category in ('push','pull','legs','core')),
  primary_muscle text not null,
  pattern text not null,
  equipment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.routine_templates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  day_order integer not null check (day_order between 1 and 7),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name),
  unique (user_id, day_order)
);

create table if not exists public.routine_exercises (
  id uuid primary key default gen_random_uuid(),
  routine_id uuid not null references public.routine_templates(id) on delete cascade,
  exercise_id bigint not null references public.exercise_library(id),
  position integer not null,
  target_sets integer not null default 2 check (target_sets between 1 and 10),
  rep_min integer not null default 8 check (rep_min between 1 and 100),
  rep_max integer not null default 12 check (rep_max between 1 and 100),
  rir_target integer not null default 3 check (rir_target between 0 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (routine_id, position)
);

create table if not exists public.workout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  routine_id uuid references public.routine_templates(id) on delete set null,
  session_date date not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_exercises (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.workout_sessions(id) on delete cascade,
  planned_routine_exercise_id uuid references public.routine_exercises(id) on delete set null,
  exercise_id bigint not null references public.exercise_library(id),
  position integer not null,
  created_at timestamptz not null default now(),
  unique (session_id, position)
);

create table if not exists public.workout_sets (
  id uuid primary key default gen_random_uuid(),
  workout_exercise_id uuid not null references public.workout_exercises(id) on delete cascade,
  set_number integer not null,
  weight_kg numeric(7,2),
  reps integer check (reps between 0 and 500),
  rir integer check (rir between 0 and 10),
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workout_exercise_id, set_number)
);

create table if not exists public.meal_templates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  calories integer not null default 0,
  protein_g integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.walking_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_date date not null,
  started_at timestamptz,
  finished_at timestamptz,
  steps integer,
  distance_km numeric(7,2),
  created_at timestamptz not null default now()
);

create index if not exists daily_logs_user_date_idx on public.daily_logs(user_id, log_date desc);
create index if not exists workout_sessions_user_date_idx on public.workout_sessions(user_id, session_date desc);
create index if not exists routine_templates_user_idx on public.routine_templates(user_id);
create index if not exists routine_exercises_routine_idx on public.routine_exercises(routine_id);
create index if not exists workout_exercises_session_idx on public.workout_exercises(session_id);
create index if not exists workout_sets_exercise_idx on public.workout_sets(workout_exercise_id);

insert into public.exercise_library (slug,name,category,primary_muscle,pattern,equipment) values
('chest-press-machine','Press de pecho en máquina','push','Pecho','Empuje horizontal','Máquina'),
('incline-dumbbell-press','Press inclinado con mancuernas','push','Pecho superior','Empuje horizontal','Mancuernas'),
('incline-machine-press','Press inclinado en máquina','push','Pecho superior','Empuje horizontal','Máquina'),
('shoulder-press-machine','Press de hombros en máquina','push','Hombros','Empuje vertical','Máquina'),
('lateral-raise','Elevaciones laterales','push','Hombro lateral','Abducción de hombro','Mancuernas'),
('cable-lateral-raise','Elevación lateral en polea','push','Hombro lateral','Abducción de hombro','Polea'),
('triceps-pushdown','Tríceps en polea','push','Tríceps','Extensión de codo','Polea'),
('overhead-triceps-extension','Extensión de tríceps sobre cabeza','push','Tríceps','Extensión de codo','Polea'),
('pec-deck','Aperturas en máquina','push','Pecho','Aducción horizontal','Máquina'),
('lat-pulldown','Lat pulldown','pull','Dorsal','Tirón vertical','Polea'),
('neutral-lat-pulldown','Lat pulldown agarre neutro','pull','Dorsal','Tirón vertical','Polea'),
('seated-row','Remo sentado','pull','Espalda media','Tirón horizontal','Polea'),
('chest-supported-row','Remo con pecho apoyado','pull','Espalda media','Tirón horizontal','Máquina'),
('one-arm-dumbbell-row','Remo con mancuerna','pull','Dorsal','Tirón horizontal','Mancuerna'),
('machine-row','Remo en máquina','pull','Espalda media','Tirón horizontal','Máquina'),
('straight-arm-pulldown','Pullover en polea','pull','Dorsal','Extensión de hombro','Polea'),
('rear-delt-fly','Rear delt fly','pull','Deltoide posterior','Abducción horizontal','Máquina'),
('face-pull','Face pull','pull','Deltoide posterior','Tirón horizontal','Polea'),
('biceps-curl','Curl de bíceps','pull','Bíceps','Flexión de codo','Mancuernas'),
('hammer-curl','Curl martillo','pull','Bíceps y braquial','Flexión de codo','Mancuernas'),
('leg-press','Prensa de piernas','legs','Cuádriceps','Dominante de rodilla','Máquina'),
('hack-squat','Hack squat','legs','Cuádriceps','Dominante de rodilla','Máquina'),
('goblet-squat','Sentadilla goblet','legs','Cuádriceps','Dominante de rodilla','Mancuerna'),
('romanian-deadlift','Peso muerto rumano','legs','Isquiotibiales','Bisagra de cadera','Mancuernas'),
('hip-thrust','Hip thrust','legs','Glúteos','Extensión de cadera','Máquina'),
('leg-extension','Extensión de cuádriceps','legs','Cuádriceps','Extensión de rodilla','Máquina'),
('leg-curl','Curl femoral','legs','Isquiotibiales','Flexión de rodilla','Máquina'),
('calf-raise','Elevación de pantorrillas','legs','Pantorrillas','Flexión plantar','Máquina'),
('walking-lunge','Zancadas caminando','legs','Pierna completa','Dominante de rodilla','Mancuernas'),
('plank','Plancha','core','Core','Anti-extensión','Peso corporal'),
('cable-crunch','Crunch en polea','core','Abdominales','Flexión de tronco','Polea')
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  primary_muscle = excluded.primary_muscle,
  pattern = excluded.pattern,
  equipment = excluded.equipment;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists daily_logs_updated_at on public.daily_logs;
create trigger daily_logs_updated_at before update on public.daily_logs for each row execute function public.set_updated_at();
drop trigger if exists routine_templates_updated_at on public.routine_templates;
create trigger routine_templates_updated_at before update on public.routine_templates for each row execute function public.set_updated_at();
drop trigger if exists routine_exercises_updated_at on public.routine_exercises;
create trigger routine_exercises_updated_at before update on public.routine_exercises for each row execute function public.set_updated_at();
drop trigger if exists workout_sessions_updated_at on public.workout_sessions;
create trigger workout_sessions_updated_at before update on public.workout_sessions for each row execute function public.set_updated_at();
drop trigger if exists workout_sets_updated_at on public.workout_sets;
create trigger workout_sets_updated_at before update on public.workout_sets for each row execute function public.set_updated_at();
drop trigger if exists meal_templates_updated_at on public.meal_templates;
create trigger meal_templates_updated_at before update on public.meal_templates for each row execute function public.set_updated_at();

create or replace function public.seed_default_routines(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  push_a uuid;
  pull_a uuid;
  legs_a uuid;
  push_b uuid;
  pull_b uuid;
  legs_b uuid;
begin
  if exists (select 1 from public.routine_templates where user_id = p_user_id) then
    return;
  end if;

  insert into public.routine_templates(user_id,name,day_order) values (p_user_id,'Push A',1) returning id into push_a;
  insert into public.routine_templates(user_id,name,day_order) values (p_user_id,'Pull A',2) returning id into pull_a;
  insert into public.routine_templates(user_id,name,day_order) values (p_user_id,'Legs A',3) returning id into legs_a;
  insert into public.routine_templates(user_id,name,day_order) values (p_user_id,'Push B',4) returning id into push_b;
  insert into public.routine_templates(user_id,name,day_order) values (p_user_id,'Pull B',5) returning id into pull_b;
  insert into public.routine_templates(user_id,name,day_order) values (p_user_id,'Legs B',6) returning id into legs_b;

  insert into public.routine_exercises(routine_id,exercise_id,position,target_sets,rep_min,rep_max,rir_target)
  select push_a,id,pos,2,rmin,rmax,3 from (values
    ('chest-press-machine',1,8,12),('incline-dumbbell-press',2,8,12),('shoulder-press-machine',3,8,12),('lateral-raise',4,12,20),('triceps-pushdown',5,10,15)
  ) v(slug,pos,rmin,rmax) join public.exercise_library e using(slug);

  insert into public.routine_exercises(routine_id,exercise_id,position,target_sets,rep_min,rep_max,rir_target)
  select pull_a,id,pos,2,rmin,rmax,3 from (values
    ('lat-pulldown',1,8,12),('seated-row',2,8,12),('chest-supported-row',3,8,12),('rear-delt-fly',4,12,20),('biceps-curl',5,10,15)
  ) v(slug,pos,rmin,rmax) join public.exercise_library e using(slug);

  insert into public.routine_exercises(routine_id,exercise_id,position,target_sets,rep_min,rep_max,rir_target)
  select legs_a,id,pos,2,rmin,rmax,3 from (values
    ('leg-press',1,8,12),('romanian-deadlift',2,8,10),('leg-curl',3,10,15),('calf-raise',4,10,15),('plank',5,30,45)
  ) v(slug,pos,rmin,rmax) join public.exercise_library e using(slug);

  insert into public.routine_exercises(routine_id,exercise_id,position,target_sets,rep_min,rep_max,rir_target)
  select push_b,id,pos,2,rmin,rmax,3 from (values
    ('incline-machine-press',1,8,12),('chest-press-machine',2,8,12),('pec-deck',3,10,15),('cable-lateral-raise',4,12,20),('overhead-triceps-extension',5,10,15)
  ) v(slug,pos,rmin,rmax) join public.exercise_library e using(slug);

  insert into public.routine_exercises(routine_id,exercise_id,position,target_sets,rep_min,rep_max,rir_target)
  select pull_b,id,pos,2,rmin,rmax,3 from (values
    ('neutral-lat-pulldown',1,8,12),('one-arm-dumbbell-row',2,8,12),('straight-arm-pulldown',3,12,15),('face-pull',4,12,20),('hammer-curl',5,10,15)
  ) v(slug,pos,rmin,rmax) join public.exercise_library e using(slug);

  insert into public.routine_exercises(routine_id,exercise_id,position,target_sets,rep_min,rep_max,rir_target)
  select legs_b,id,pos,2,rmin,rmax,3 from (values
    ('hack-squat',1,8,12),('hip-thrust',2,8,12),('leg-extension',3,10,15),('leg-curl',4,10,15),('calf-raise',5,10,15)
  ) v(slug,pos,rmin,rmax) join public.exercise_library e using(slug);

  insert into public.meal_templates(user_id,name,calories,protein_g) values
    (p_user_id,'Batido de proteína',250,30),
    (p_user_id,'Pollo + ensalada',480,50),
    (p_user_id,'Atún + huevos',420,42),
    (p_user_id,'Cena Shabat estimada',800,55);
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id,display_name,timezone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1)),
    coalesce(new.raw_user_meta_data->>'timezone','America/Santiago')
  )
  on conflict (id) do nothing;
  perform public.seed_default_routines(new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- Crear perfil/rutinas para usuarios que ya existían antes de ejecutar este archivo.
insert into public.profiles(id,display_name)
select id, coalesce(raw_user_meta_data->>'display_name', split_part(email,'@',1))
from auth.users
on conflict (id) do nothing;

do $$
declare r record;
begin
  for r in select id from public.profiles loop
    perform public.seed_default_routines(r.id);
  end loop;
end $$;

alter table public.profiles enable row level security;
alter table public.daily_logs enable row level security;
alter table public.exercise_library enable row level security;
alter table public.routine_templates enable row level security;
alter table public.routine_exercises enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_exercises enable row level security;
alter table public.workout_sets enable row level security;
alter table public.meal_templates enable row level security;
alter table public.walking_sessions enable row level security;

-- Borra políticas previas para que el script pueda volver a ejecutarse.
drop policy if exists "profiles own select" on public.profiles;
drop policy if exists "profiles own update" on public.profiles;
drop policy if exists "daily logs own all" on public.daily_logs;
drop policy if exists "exercise library read" on public.exercise_library;
drop policy if exists "routine templates own all" on public.routine_templates;
drop policy if exists "routine exercises own select" on public.routine_exercises;
drop policy if exists "routine exercises own insert" on public.routine_exercises;
drop policy if exists "routine exercises own update" on public.routine_exercises;
drop policy if exists "routine exercises own delete" on public.routine_exercises;
drop policy if exists "workout sessions own all" on public.workout_sessions;
drop policy if exists "workout exercises own select" on public.workout_exercises;
drop policy if exists "workout exercises own insert" on public.workout_exercises;
drop policy if exists "workout exercises own update" on public.workout_exercises;
drop policy if exists "workout exercises own delete" on public.workout_exercises;
drop policy if exists "workout sets own select" on public.workout_sets;
drop policy if exists "workout sets own insert" on public.workout_sets;
drop policy if exists "workout sets own update" on public.workout_sets;
drop policy if exists "workout sets own delete" on public.workout_sets;
drop policy if exists "meal templates own all" on public.meal_templates;
drop policy if exists "walking sessions own all" on public.walking_sessions;

create policy "profiles own select" on public.profiles for select using (auth.uid() = id);
create policy "profiles own update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "daily logs own all" on public.daily_logs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "exercise library read" on public.exercise_library for select to authenticated using (true);
create policy "routine templates own all" on public.routine_templates for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "routine exercises own select" on public.routine_exercises for select using (
  exists (select 1 from public.routine_templates r where r.id = routine_id and r.user_id = auth.uid())
);
create policy "routine exercises own insert" on public.routine_exercises for insert with check (
  exists (select 1 from public.routine_templates r where r.id = routine_id and r.user_id = auth.uid())
);
create policy "routine exercises own update" on public.routine_exercises for update using (
  exists (select 1 from public.routine_templates r where r.id = routine_id and r.user_id = auth.uid())
) with check (
  exists (select 1 from public.routine_templates r where r.id = routine_id and r.user_id = auth.uid())
);
create policy "routine exercises own delete" on public.routine_exercises for delete using (
  exists (select 1 from public.routine_templates r where r.id = routine_id and r.user_id = auth.uid())
);

create policy "workout sessions own all" on public.workout_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "workout exercises own select" on public.workout_exercises for select using (
  exists (select 1 from public.workout_sessions s where s.id = session_id and s.user_id = auth.uid())
);
create policy "workout exercises own insert" on public.workout_exercises for insert with check (
  exists (select 1 from public.workout_sessions s where s.id = session_id and s.user_id = auth.uid())
);
create policy "workout exercises own update" on public.workout_exercises for update using (
  exists (select 1 from public.workout_sessions s where s.id = session_id and s.user_id = auth.uid())
) with check (
  exists (select 1 from public.workout_sessions s where s.id = session_id and s.user_id = auth.uid())
);
create policy "workout exercises own delete" on public.workout_exercises for delete using (
  exists (select 1 from public.workout_sessions s where s.id = session_id and s.user_id = auth.uid())
);

create policy "workout sets own select" on public.workout_sets for select using (
  exists (
    select 1 from public.workout_exercises we
    join public.workout_sessions s on s.id = we.session_id
    where we.id = workout_exercise_id and s.user_id = auth.uid()
  )
);
create policy "workout sets own insert" on public.workout_sets for insert with check (
  exists (
    select 1 from public.workout_exercises we
    join public.workout_sessions s on s.id = we.session_id
    where we.id = workout_exercise_id and s.user_id = auth.uid()
  )
);
create policy "workout sets own update" on public.workout_sets for update using (
  exists (
    select 1 from public.workout_exercises we
    join public.workout_sessions s on s.id = we.session_id
    where we.id = workout_exercise_id and s.user_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.workout_exercises we
    join public.workout_sessions s on s.id = we.session_id
    where we.id = workout_exercise_id and s.user_id = auth.uid()
  )
);
create policy "workout sets own delete" on public.workout_sets for delete using (
  exists (
    select 1 from public.workout_exercises we
    join public.workout_sessions s on s.id = we.session_id
    where we.id = workout_exercise_id and s.user_id = auth.uid()
  )
);

create policy "meal templates own all" on public.meal_templates for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "walking sessions own all" on public.walking_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles, public.daily_logs, public.routine_templates, public.routine_exercises, public.workout_sessions, public.workout_exercises, public.workout_sets, public.meal_templates, public.walking_sessions to authenticated;
grant select on public.exercise_library to authenticated;
grant usage, select on all sequences in schema public to authenticated;
